$(document).ready(function(){$('.tab-control.home-tab > ul > li > a').click(function(event){var $this=$(this);var $target=$this.attr('href');$('.tab-control.home-tab > ul > li').removeClass('active');$this.parent().addClass('active');$('.home-tab-panel > .list_movie').removeClass('active');$($target).addClass('active');var $this2=$($target);var li=$this2.find('ul').html();if(!li){var $phim=$this2.data('phim');dh_request_film_tab($phim,1,$this2);}
return false;});$(document).on('click','.home-pagination a',function(event){var $this=$(this);var page=$this.attr('href').replace(/\D/g,'');var target=$this.closest('.list_movie');var type=target.data('phim');dh_request_film_tab(type,page,target);return false;});$('#dt-bottom-right-banner').hover(function(){$('#dt-bottom-right-banner > a').stop().show();$('#dt-bottom-right-banner > .close').css('display','block');},function(){$('#dt-bottom-right-banner > a').stop().hide();$('#dt-bottom-right-banner > .close').stop().hide();});$('#dt-bottom-right-banner > .close').click(function(event){$('#dt-bottom-right-banner').hide();$('#dt-bottom-right-banner > .close').stop().hide();$('#dt-bottom-right-banner > a').stop().hide();});var totalCheck=1;var maxCheck=5;var $notibox=$(".notibox");$("a[href='#thongbao']").click(function(e){e.preventDefault();var page=jQuery('#list_notifications').attr('data-nextpage');$notibox.show();jQuery("#header li.headerInfo a.viewallnoti").show();jQuery('.notibox-up-arrow').show();jQuery('#overlay').show();jQuery('#overlay').click(function(event){$notibox.hide();jQuery("#header li.headerInfo a.viewallnoti").hide();jQuery('.notibox-up-arrow').hide();jQuery('#overlay').hide();});if($notibox.hasClass('ur')){ajax_get_notifications(page);}});$('#list_notifications').bind('scroll',function(){var page=jQuery('#list_notifications').attr('data-nextpage');if($(this).scrollTop()+ $(this).innerHeight()>=this.scrollHeight){ajax_get_notifications(page);}})
function ajax_get_notifications(page){jQuery('#list_notifications > li.view_all_notification').remove();if(page<=maxCheck&&page>0&&totalCheck<=maxCheck){$.post(ajaxurl,{gnarty_get_nofitications:page,},function(a){var $data=$.parseJSON(a);if(!$data.error){jQuery('.badge.badge-default').css('display','none');if($data.html.trim()){jQuery('#list_notifications').append($data.html).attr('data-nextpage',$data.nextpage);jQuery('.no_new_noti').remove();$notibox.addClass('seen');totalCheck++;}else{$('#list_notifications').unbind('scroll');totalCheck=maxCheck+ 1;}}})}else{if(page==0){$('#list_notifications').unbind('scroll');totalCheck=maxCheck+ 1;}}}
$("button[id='btnFollow']").on('click',function(){var phimid_fl=$(this).attr('data-phimid');if($(this).attr('data-text')=='xoatheodoi'){_FollowLoad(0,phimid_fl);$(this).text("Theo dõi");$(this).attr('data-text','theodoi');}else{_FollowLoad(phimid_fl,0);$(this).text("Bỏ theo dõi");$(this).attr('data-text','xoatheodoi')}});$("button[id='btnViewed']").on('click',function(){var phimid_view=$(this).attr('data-phimid');if($(this).attr('data-text')=='chuaxem'){_watchingFilmLoad(phimid_view,0);$(this).text("Đang xem");$(this).attr('data-text','dangxem');$(this).removeClass('chuaxem').addClass('dangxem');}else if($(this).attr('data-text')=='dangxem'){_ViewedLoad(phimid_view,0);_watchingFilmLoad(0,phimid_view);$(this).text("Đã xem");$(this).attr('data-text','daxem');$(this).removeClass('dangxem').addClass('daxem');}else if($(this).attr('data-text')=='daxem'){_ViewedLoad(0,phimid_view);$(this).text("Chưa xem");$(this).attr('data-text','chuaxem');$(this).removeClass('daxem').addClass('chuaxem');}});jQuery('#offads, .gnarty-home-off-ads').click(function(event){jQuery('.gnarty-offads').remove();return false;});jQuery('.list-acd-group table tr a.see-more').click(function(event){var t=jQuery(this).text();if(t=='Xem thêm >'){jQuery(this).text('Rút gọn');}else{jQuery(this).text('Xem thêm >');}
jQuery('.list-acd-group table tr.dynamic').toggle();});jQuery('.gtab-title').click(function(event){var $target=jQuery(this).data('target');jQuery('.gtab-title').removeClass('active');jQuery(this).addClass('active');jQuery('.gtab-content').removeClass('active');jQuery($target).addClass('active');});jQuery('.gtab ul.nav-tabs li a').click(function(event){var parent=jQuery(this).parent();if(!parent.hasClass('not_tab')){jQuery('.gtab ul.nav-tabs li').removeClass('active');jQuery(this).parent().addClass('active');var $target=jQuery(this).data('href');jQuery('.gtab .tab-content .tab-pane').removeClass('active').hide();jQuery($target).addClass('active').show();return false;}});$('.items').each(function(){var xOffset=-10;var yOffset=10;$(this).unbind().hover(function(e){this.content=$(this).parent().find('.f-description').html();this.top=(e.pageY+ yOffset);this.left=(e.pageX+ xOffset);if(this.content!=null){$('body').append('<div id="vtip" class="f-description">'+ this.content+'</div>');$('div#vtip').css("top",this.top+"px").css("left",this.left+"px").fadeIn("slow");}},function(){$("div#vtip").fadeOut("slow").remove();}).mousemove(function(e){this.top=(e.pageY+ yOffset);this.left=(e.pageX+ xOffset);$("div#vtip").css("top",this.top+"px").css("left",this.left+"px");});});$("#help-box").click(function(){$("#support-box").show();});$("#support-box").hover(function(){},function(){$(this).hide("fast");});$("#facebook-pannel-btn").click(function(){$("#facebook-box").show();});$("#facebook-box").hover(function(){},function(){$(this).hide("fast");});})
var Cufon=(function(){var m=function(){return m.replace.apply(null,arguments)};var x=m.DOM={ready:(function(){var C=false,E={loaded:1,complete:1};var B=[],D=function(){if(C){return}
C=true;for(var F;F=B.shift();F()){}};if(document.addEventListener){document.addEventListener("DOMContentLoaded",D,false);window.addEventListener("pageshow",D,false)}
if(!window.opera&&document.readyState){(function(){E[document.readyState]?D():setTimeout(arguments.callee,10)})()}
if(document.readyState&&document.createStyleSheet){(function(){try{document.body.doScroll("left");D()}catch(F){setTimeout(arguments.callee,1)}})()}
q(window,"load",D);return function(F){if(!arguments.length){D()}else{C?F():B.push(F)}}})(),root:function(){return document.documentElement||document.body}};var n=m.CSS={Size:function(C,B){this.value=parseFloat(C);this.unit=String(C).match(/[a-z%]*$/)[0]||"px";this.convert=function(D){return D/B*this.value};this.convertFrom=function(D){return D/this.value*B};this.toString=function(){return this.value+ this.unit}},addClass:function(C,B){var D=C.className;C.className=D+(D&&" ")+ B;return C},color:j(function(C){var B={};B.color=C.replace(/^rgba\((.*?),\s*([\d.]+)\)/,function(E,D,F){B.opacity=parseFloat(F);return"rgb("+ D+")"});return B}),fontStretch:j(function(B){if(typeof B=="number"){return B}
if(/%$/.test(B)){return parseFloat(B)/ 100
}
return{"ultra-condensed":0.5,"extra-condensed":0.625,condensed:0.75,"semi-condensed":0.875,"semi-expanded":1.125,expanded:1.25,"extra-expanded":1.5,"ultra-expanded":2}[B]||1}),getStyle:function(C){var B=document.defaultView;if(B&&B.getComputedStyle){return new a(B.getComputedStyle(C,null))}
if(C.currentStyle){return new a(C.currentStyle)}
return new a(C.style)},gradient:j(function(F){var G={id:F,type:F.match(/^-([a-z]+)-gradient\(/)[1],stops:[]},C=F.substr(F.indexOf("(")).match(/([\d.]+=)?(#[a-f0-9]+|[a-z]+\(.*?\)|[a-z]+)/ig);for(var E=0,B=C.length,D;E<B;++E){D=C[E].split("=",2).reverse();G.stops.push([D[1]||E/(B- 1),D[0]])}
return G}),quotedList:j(function(E){var D=[],C=/\s*((["'])([\s\S]*?[^\\])\2|[^,]+)\s*/g,B;while(B=C.exec(E)){D.push(B[3]||B[1])}
return D}),recognizesMedia:j(function(G){var E=document.createElement("style"),D,C,B;E.type="text/css";E.media=G;try{E.appendChild(document.createTextNode("/**/"))}catch(F){}
C=g("head")[0];C.insertBefore(E,C.firstChild);D=(E.sheet||E.styleSheet);B=D&&!D.disabled;C.removeChild(E);return B}),removeClass:function(D,C){var B=RegExp("(?:^|\\s+)"+ C+"(?=\\s|$)","g");D.className=D.className.replace(B,"");return D},supports:function(D,C){var B=document.createElement("span").style;if(B[D]===undefined){return false}
B[D]=C;return B[D]===C},textAlign:function(E,D,B,C){if(D.get("textAlign")=="right"){if(B>0){E=" "+ E}}else{if(B<C- 1){E+=" "}}
return E},textShadow:j(function(F){if(F=="none"){return null}
var E=[],G={},B,C=0;var D=/(#[a-f0-9]+|[a-z]+\(.*?\)|[a-z]+)|(-?[\d.]+[a-z%]*)|,/ig;while(B=D.exec(F)){if(B[0]==","){E.push(G);G={};C=0}else{if(B[1]){G.color=B[1]}else{G[["offX","offY","blur"][C++]]=B[2]}}}
E.push(G);return E}),textTransform:(function(){var B={uppercase:function(C){return C.toUpperCase()},lowercase:function(C){return C.toLowerCase()},capitalize:function(C){return C.replace(/\b./g,function(D){return D.toUpperCase()})}};return function(E,D){var C=B[D.get("textTransform")];return C?C(E):E}})(),whiteSpace:(function(){var D={inline:1,"inline-block":1,"run-in":1};var C=/^\s+/,B=/\s+$/;return function(H,F,G,E){if(E){if(E.nodeName.toLowerCase()=="br"){H=H.replace(C,"")}}
if(D[F.get("display")]){return H}
if(!G.previousSibling){H=H.replace(C,"")}
if(!G.nextSibling){H=H.replace(B,"")}
return H}})()};n.ready=(function(){var B=!n.recognizesMedia("all"),E=false;var D=[],H=function(){B=true;for(var K;K=D.shift();K()){}};var I=g("link"),J=g("style");function C(K){return K.disabled||G(K.sheet,K.media||"screen")}
function G(M,P){if(!n.recognizesMedia(P||"all")){return true}
if(!M||M.disabled){return false}
try{var Q=M.cssRules,O;if(Q){search:for(var L=0,K=Q.length;O=Q[L],L<K;++L){switch(O.type){case 2:break;case 3:if(!G(O.styleSheet,O.media.mediaText)){return false}
break;default:break search}}}}catch(N){}
return true}
function F(){if(document.createStyleSheet){return true}
var L,K;for(K=0;L=I[K];++K){if(L.rel.toLowerCase()=="stylesheet"&&!C(L)){return false}}
for(K=0;L=J[K];++K){if(!C(L)){return false}}
return true}
x.ready(function(){if(!E){E=n.getStyle(document.body).isUsable()}
if(B||(E&&F())){H()}else{setTimeout(arguments.callee,10)}});return function(K){if(B){K()}else{D.push(K)}}})();function s(D){var C=this.face=D.face,B={"\u0020":1,"\u00a0":1,"\u3000":1};this.glyphs=D.glyphs;this.w=D.w;this.baseSize=parseInt(C["units-per-em"],10);this.family=C["font-family"].toLowerCase();this.weight=C["font-weight"];this.style=C["font-style"]||"normal";this.viewBox=(function(){var F=C.bbox.split(/\s+/);var E={minX:parseInt(F[0],10),minY:parseInt(F[1],10),maxX:parseInt(F[2],10),maxY:parseInt(F[3],10)};E.width=E.maxX- E.minX;E.height=E.maxY- E.minY;E.toString=function(){return[this.minX,this.minY,this.width,this.height].join(" ")};return E})();this.ascent=-parseInt(C.ascent,10);this.descent=-parseInt(C.descent,10);this.height=-this.ascent+ this.descent;this.spacing=function(L,N,E){var O=this.glyphs,M,K,G,P=[],F=0,J=-1,I=-1,H;while(H=L[++J]){M=O[H]||this.missingGlyph;if(!M){continue}
if(K){F-=G=K[H]||0;P[I]-=G}
F+=P[++I]=~~(M.w||this.w)+ N+(B[H]?E:0);K=M.k}
P.total=F;return P}}
function f(){var C={},B={oblique:"italic",italic:"oblique"};this.add=function(D){(C[D.style]||(C[D.style]={}))[D.weight]=D};this.get=function(H,I){var G=C[H]||C[B[H]]||C.normal||C.italic||C.oblique;if(!G){return null}
I={normal:400,bold:700}[I]||parseInt(I,10);if(G[I]){return G[I]}
var E={1:1,99:0}[I%100],K=[],F,D;if(E===undefined){E=I>400}
if(I==500){I=400}
for(var J in G){if(!k(G,J)){continue}
J=parseInt(J,10);if(!F||J<F){F=J}
if(!D||J>D){D=J}
K.push(J)}
if(I<F){I=F}
if(I>D){I=D}
K.sort(function(M,L){return(E?(M>=I&&L>=I)?M<L:M>L:(M<=I&&L<=I)?M>L:M<L)?-1:1});return G[K[0]]}}
function r(){function D(F,G){if(F.contains){return F.contains(G)}
return F.compareDocumentPosition(G)&16}
function B(G){var F=G.relatedTarget;if(!F||D(this,F)){return}
C(this,G.type=="mouseover")}
function E(F){C(this,F.type=="mouseenter")}
function C(F,G){setTimeout(function(){var H=d.get(F).options;m.replace(F,G?h(H,H.hover):H,true)},10)}
this.attach=function(F){if(F.onmouseenter===undefined){q(F,"mouseover",B);q(F,"mouseout",B)}else{q(F,"mouseenter",E);q(F,"mouseleave",E)}}}
function u(){var C=[],D={};function B(H){var E=[],G;for(var F=0;G=H[F];++F){E[F]=C[D[G]]}
return E}
this.add=function(F,E){D[F]=C.push(E)- 1};this.repeat=function(){var E=arguments.length?B(arguments):C,F;for(var G=0;F=E[G++];){m.replace(F[0],F[1],true)}}}
function A(){var D={},B=0;function C(E){return E.cufid||(E.cufid=++B)}
this.get=function(E){var F=C(E);return D[F]||(D[F]={})}}
function a(B){var D={},C={};this.extend=function(E){for(var F in E){if(k(E,F)){D[F]=E[F]}}
return this};this.get=function(E){return D[E]!=undefined?D[E]:B[E]};this.getSize=function(F,E){return C[F]||(C[F]=new n.Size(this.get(F),E))};this.isUsable=function(){return!!B}}
function q(C,B,D){if(C.addEventListener){C.addEventListener(B,D,false)}else{if(C.attachEvent){C.attachEvent("on"+ B,function(){return D.call(C,window.event)})}}}
function v(C,B){var D=d.get(C);if(D.options){return C}
if(B.hover&&B.hoverables[C.nodeName.toLowerCase()]){b.attach(C)}
D.options=B;return C}
function j(B){var C={};return function(D){if(!k(C,D)){C[D]=B.apply(null,arguments)}
return C[D]}}
function c(F,E){var B=n.quotedList(E.get("fontFamily").toLowerCase()),D;for(var C=0;D=B[C];++C){if(i[D]){return i[D].get(E.get("fontStyle"),E.get("fontWeight"))}}
return null}
function g(B){return document.getElementsByTagName(B)}
function k(C,B){return C.hasOwnProperty(B)}
function h(){var C={},B,F;for(var E=0,D=arguments.length;B=arguments[E],E<D;++E){for(F in B){if(k(B,F)){C[F]=B[F]}}}
return C}
function o(E,M,C,N,F,D){var K=document.createDocumentFragment(),H;if(M===""){return K}
var L=N.separate;var I=M.split(p[L]),B=(L=="words");if(B&&t){if(/^\s/.test(M)){I.unshift("")}
if(/\s$/.test(M)){I.push("")}}
for(var J=0,G=I.length;J<G;++J){H=z[N.engine](E,B?n.textAlign(I[J],C,J,G):I[J],C,N,F,D,J<G- 1);if(H){K.appendChild(H)}}
return K}
function l(D,M){var C=D.nodeName.toLowerCase();if(M.ignore[C]){return}
var E=!M.textless[C];var B=n.getStyle(v(D,M)).extend(M);var F=c(D,B),G,K,I,H,L,J;if(!F){return}
for(G=D.firstChild;G;G=I){K=G.nodeType;I=G.nextSibling;if(E&&K==3){if(H){H.appendData(G.data);D.removeChild(G)}else{H=G}
if(I){continue}}
if(H){D.replaceChild(o(F,n.whiteSpace(H.data,B,H,J),B,M,G,D),H);H=null}
if(K==1){if(G.firstChild){if(G.nodeName.toLowerCase()=="cufon"){z[M.engine](F,null,B,M,G,D)}else{arguments.callee(G,M)}}
J=G}}}
var t=" ".split(/\s+/).length==0;var d=new A();var b=new r();var y=new u();var e=false;var z={},i={},w={autoDetect:false,engine:null,forceHitArea:false,hover:false,hoverables:{a:true},ignore:{applet:1,canvas:1,col:1,colgroup:1,head:1,iframe:1,map:1,optgroup:1,option:1,script:1,select:1,style:1,textarea:1,title:1,pre:1},printable:true,selector:(window.Sizzle||(window.jQuery&&function(B){return jQuery(B)})||(window.dojo&&dojo.query)||(window.Ext&&Ext.query)||(window.YAHOO&&YAHOO.util&&YAHOO.util.Selector&&YAHOO.util.Selector.query)||(window.$$&&function(B){return $$(B)})||(window.$&&function(B){return $(B)})||(document.querySelectorAll&&function(B){return document.querySelectorAll(B)})||g),separate:"words",textless:{dl:1,html:1,ol:1,table:1,tbody:1,thead:1,tfoot:1,tr:1,ul:1},textShadow:"none"};var p={words:/\s/.test("\u00a0")?/[^\S\u00a0]+/:/\s+/,characters:"",none:/^/};m.now=function(){x.ready();return m};m.refresh=function(){y.repeat.apply(y,arguments);return m};m.registerEngine=function(C,B){if(!B){return m}
z[C]=B;return m.set("engine",C)};m.registerFont=function(D){if(!D){return m}
var B=new s(D),C=B.family;if(!i[C]){i[C]=new f()}
i[C].add(B);return m.set("fontFamily",'"'+ C+'"')};m.replace=function(D,C,B){C=h(w,C);if(!C.engine){return m}
if(!e){n.addClass(x.root(),"cufon-active cufon-loading");n.ready(function(){n.addClass(n.removeClass(x.root(),"cufon-loading"),"cufon-ready")});e=true}
if(C.hover){C.forceHitArea=true}
if(C.autoDetect){delete C.fontFamily}
if(typeof C.textShadow=="string"){C.textShadow=n.textShadow(C.textShadow)}
if(typeof C.color=="string"&&/^-/.test(C.color)){C.textGradient=n.gradient(C.color)}else{delete C.textGradient}
if(!B){y.add(D,arguments)}
if(D.nodeType||typeof D=="string"){D=[D]}
n.ready(function(){for(var F=0,E=D.length;F<E;++F){var G=D[F];if(typeof G=="string"){m.replace(C.selector(G),C,true)}else{l(G,C)}}});return m};m.set=function(B,C){w[B]=C;return m};return m})();Cufon.registerEngine("vml",(function(){var e=document.namespaces;if(!e){return}
e.add("cvml","urn:schemas-microsoft-com:vml");e=null;var b=document.createElement("cvml:shape");b.style.behavior="url(#default#VML)";if(!b.coordsize){return}
b=null;var h=(document.documentMode||0)<8;document.write(('<style type="text/css">cufoncanvas{text-indent:0;}@media screen{cvml\\:shape,cvml\\:rect,cvml\\:fill,cvml\\:shadow{behavior:url(#default#VML);display:block;antialias:true;position:absolute;}cufoncanvas{position:absolute;text-align:left;}cufon{display:inline-block;position:relative;vertical-align:'+(h?"middle":"text-bottom")+";}cufon cufontext{position:absolute;left:-10000in;font-size:1px;}a cufon{cursor:pointer}}@media print{cufon cufoncanvas{display:none;}}</style>").replace(/;/g,"!important;"));function c(i,j){return a(i,/(?:em|ex|%)$|^[a-z-]+$/i.test(j)?"1em":j)}
function a(l,m){if(m==="0"){return 0}
if(/px$/i.test(m)){return parseFloat(m)}
var k=l.style.left,j=l.runtimeStyle.left;l.runtimeStyle.left=l.currentStyle.left;l.style.left=m.replace("%","em");var i=l.style.pixelLeft;l.style.left=k;l.runtimeStyle.left=j;return i}
function f(l,k,j,n){var i="computed"+ n,m=k[i];if(isNaN(m)){m=k.get(n);k[i]=m=(m=="normal")?0:~~j.convertFrom(a(l,m))}
return m}
var g={};function d(p){var q=p.id;if(!g[q]){var n=p.stops,o=document.createElement("cvml:fill"),i=[];o.type="gradient";o.angle=180;o.focus="0";o.method="sigma";o.color=n[0][1];for(var m=1,l=n.length- 1;m<l;++m){i.push(n[m][0]*100+"% "+ n[m][1])}
o.colors=i.join(",");o.color2=n[l][1];g[q]=o}
return g[q]}
return function(ac,G,Y,C,K,ad,W){var n=(G===null);if(n){G=K.alt}
var I=ac.viewBox;var p=Y.computedFontSize||(Y.computedFontSize=new Cufon.CSS.Size(c(ad,Y.get("fontSize"))+"px",ac.baseSize));var y,q;if(n){y=K;q=K.firstChild}else{y=document.createElement("cufon");y.className="cufon cufon-vml";y.alt=G;q=document.createElement("cufoncanvas");y.appendChild(q);if(C.printable){var Z=document.createElement("cufontext");Z.appendChild(document.createTextNode(G));y.appendChild(Z)}
if(!W){y.appendChild(document.createElement("cvml:shape"))}}
var ai=y.style;var R=q.style;var l=p.convert(I.height),af=Math.ceil(l);var V=af/l;var P=V*Cufon.CSS.fontStretch(Y.get("fontStretch"));var U=I.minX,T=I.minY;R.height=af;R.top=Math.round(p.convert(T- ac.ascent));R.left=Math.round(p.convert(U));ai.height=p.convert(ac.height)+"px";var F=Y.get("color");var ag=Cufon.CSS.textTransform(G,Y).split("");var L=ac.spacing(ag,f(ad,Y,p,"letterSpacing"),f(ad,Y,p,"wordSpacing"));if(!L.length){return null}
var k=L.total;var x=-U+ k+(I.width- L[L.length- 1]);var ah=p.convert(x*P),X=Math.round(ah);var O=x+","+ I.height,m;var J="r"+ O+"ns";var u=C.textGradient&&d(C.textGradient);var o=ac.glyphs,S=0;var H=C.textShadow;var ab=-1,aa=0,w;while(w=ag[++ab]){var D=o[ag[ab]]||ac.missingGlyph,v;if(!D){continue}
if(n){v=q.childNodes[aa];while(v.firstChild){v.removeChild(v.firstChild)}}else{v=document.createElement("cvml:shape");q.appendChild(v)}
v.stroked="f";v.coordsize=O;v.coordorigin=m=(U- S)+","+ T;v.path=(D.d?"m"+ D.d+"xe":"")+"m"+ m+ J;v.fillcolor=F;if(u){v.appendChild(u.cloneNode(false))}
var ae=v.style;ae.width=X;ae.height=af;if(H){var s=H[0],r=H[1];var B=Cufon.CSS.color(s.color),z;var N=document.createElement("cvml:shadow");N.on="t";N.color=B.color;N.offset=s.offX+","+ s.offY;if(r){z=Cufon.CSS.color(r.color);N.type="double";N.color2=z.color;N.offset2=r.offX+","+ r.offY}
N.opacity=B.opacity||(z&&z.opacity)||1;v.appendChild(N)}
S+=L[aa++]}
var M=v.nextSibling,t,A;if(C.forceHitArea){if(!M){M=document.createElement("cvml:rect");M.stroked="f";M.className="cufon-vml-cover";t=document.createElement("cvml:fill");t.opacity=0;M.appendChild(t);q.appendChild(M)}
A=M.style;A.width=X;A.height=af}else{if(M){q.removeChild(M)}}
ai.width=Math.max(Math.ceil(p.convert(k*P)),0);if(h){var Q=Y.computedYAdjust;if(Q===undefined){var E=Y.get("lineHeight");if(E=="normal"){E="1em"}else{if(!isNaN(E)){E+="em"}}
Y.computedYAdjust=Q=0.5*(a(ad,E)- parseFloat(ai.height))}
if(Q){ai.marginTop=Math.ceil(Q)+"px";ai.marginBottom=Q+"px"}}
return y}})());Cufon.registerEngine("canvas",(function(){var b=document.createElement("canvas");if(!b||!b.getContext||!b.getContext.apply){return}
b=null;var a=Cufon.CSS.supports("display","inline-block");var e=!a&&(document.compatMode=="BackCompat"||/frameset|transitional/i.test(document.doctype.publicId));var f=document.createElement("style");f.type="text/css";f.appendChild(document.createTextNode(("cufon{text-indent:0;}@media screen,projection{cufon{display:inline;display:inline-block;position:relative;vertical-align:middle;"+(e?"":"font-size:1px;line-height:1px;")+"}cufon cufontext{display:-moz-inline-box;display:inline-block;width:0;height:0;overflow:hidden;text-indent:-10000in;}"+(a?"cufon canvas{position:relative;}":"cufon canvas{position:absolute;}")+"}@media print{cufon{padding:0;}cufon canvas{display:none;}}").replace(/;/g,"!important;")));document.getElementsByTagName("head")[0].appendChild(f);function d(p,h){var n=0,m=0;var g=[],o=/([mrvxe])([^a-z]*)/g,k;generate:for(var j=0;k=o.exec(p);++j){var l=k[2].split(",");switch(k[1]){case"v":g[j]={m:"bezierCurveTo",a:[n+~~l[0],m+~~l[1],n+~~l[2],m+~~l[3],n+=~~l[4],m+=~~l[5]]};break;case"r":g[j]={m:"lineTo",a:[n+=~~l[0],m+=~~l[1]]};break;case"m":g[j]={m:"moveTo",a:[n=~~l[0],m=~~l[1]]};break;case"x":g[j]={m:"closePath"};break;case"e":break generate}
h[g[j].m].apply(h,g[j].a)}
return g}
function c(m,k){for(var j=0,h=m.length;j<h;++j){var g=m[j];k[g.m].apply(k,g.a)}}
return function(V,w,P,t,C,W){var k=(w===null);if(k){w=C.getAttribute("alt")}
var A=V.viewBox;var m=P.getSize("fontSize",V.baseSize);var B=0,O=0,N=0,u=0;var z=t.textShadow,L=[];if(z){for(var U=z.length;U--;){var F=z[U];var K=m.convertFrom(parseFloat(F.offX));var I=m.convertFrom(parseFloat(F.offY));L[U]=[K,I];if(I<B){B=I}
if(K>O){O=K}
if(I>N){N=I}
if(K<u){u=K}}}
var Z=Cufon.CSS.textTransform(w,P).split("");var E=V.spacing(Z,~~m.convertFrom(parseFloat(P.get("letterSpacing"))||0),~~m.convertFrom(parseFloat(P.get("wordSpacing"))||0));if(!E.length){return null}
var h=E.total;O+=A.width- E[E.length- 1];u+=A.minX;var s,n;if(k){s=C;n=C.firstChild}else{s=document.createElement("cufon");s.className="cufon cufon-canvas";s.setAttribute("alt",w);n=document.createElement("canvas");s.appendChild(n);if(t.printable){var S=document.createElement("cufontext");S.appendChild(document.createTextNode(w));s.appendChild(S)}}
var aa=s.style;var H=n.style;var j=m.convert(A.height);var Y=Math.ceil(j);var M=Y/j;var G=M*Cufon.CSS.fontStretch(P.get("fontStretch"));var J=h*G;var Q=Math.ceil(m.convert(J+ O- u));var o=Math.ceil(m.convert(A.height- B+ N));n.width=Q;n.height=o;H.width=Q+"px";H.height=o+"px";B+=A.minY;H.top=Math.round(m.convert(B- V.ascent))+"px";H.left=Math.round(m.convert(u))+"px";var r=Math.max(Math.ceil(m.convert(J)),0)+"px";if(a){aa.width=r;aa.height=m.convert(V.height)+"px"}else{aa.paddingLeft=r;aa.paddingBottom=(m.convert(V.height)- 1)+"px"}
var X=n.getContext("2d"),D=j/A.height;X.scale(D,D*M);X.translate(-u,-B);X.save();function T(){var x=V.glyphs,ab,l=-1,g=-1,y;X.scale(G,1);while(y=Z[++l]){var ab=x[Z[l]]||V.missingGlyph;if(!ab){continue}
if(ab.d){X.beginPath();if(ab.code){c(ab.code,X)}else{ab.code=d("m"+ ab.d,X)}
X.fill()}
X.translate(E[++g],0)}
X.restore()}
if(z){for(var U=z.length;U--;){var F=z[U];X.save();X.fillStyle=F.color;X.translate.apply(X,L[U]);T()}}
var q=t.textGradient;if(q){var v=q.stops,p=X.createLinearGradient(0,A.minY,0,A.maxY);for(var U=0,R=v.length;U<R;++U){p.addColorStop.apply(p,v[U])}
X.fillStyle=p}else{X.fillStyle=P.get("color")}
T();return s}})());Cufon.replace('.cufont');function blink(selector){$(selector).fadeOut('slow',function(){$(this).fadeIn('slow',function(){blink(this);});});}
blink('.listep a.playing');function apprise(a,b,c,d){var e={confirm:false,verify:false,input:false,animate:false,textOk:"Ok",textCancel:"Đóng",textYes:"Có",textNo:"Không"};if(c){for(var f in e){if(typeof c[f]=="undefined")c[f]=e[f]}}
var g=$(document).height();var h=$(document).width();$(".appriseOverlay").remove();$(".appriseOuter").remove();$("body").append('<div class="appriseOverlay" id="aOverlay"></div>');$(".appriseOverlay").css("height",g).css("width",h).fadeIn(200);$("body").append('<div class="appriseOuter"></div>');$(".appriseOuter").append("<h2>"+ a+'</h2><a title="Nhấn Esc để thoát" class="close"></a>');Cufon.replace('.appriseOuter h2');$(".appriseOuter").append('<div class="appriseInner"></div>');$(".appriseInner").append(b);$(".appriseOuter").append('<div class="iposbottom"></div>');$(".appriseOuter").css("left",($(window).width()- $(".appriseOuter").width())/ 2 + $(window).scrollLeft() + "px");
if(c){if(c["animate"]){var i=c["animate"];if(isNaN(i)){i=400}
$(".appriseOuter").css("top","-200px").css("top","20%").fadeIn(200)}else{$(".appriseOuter").css("top","100px").fadeIn(200)}}else{$(".appriseOuter").css("top","100px").fadeIn(200)}
if(c){if(c["input"]){if(typeof c["input"]=="string"){$(".iposbottom").append('<div class="aInput"><input type="text" class="aTextbox" t="aTextbox" value="'+ c["input"]+'" /></div>')}else{$(".iposbottom").append('<div class="aInput"><input type="text" class="aTextbox" t="aTextbox" /></div>')}
$(".aTextbox").focus()}}
$(".iposbottom").append('<div class="aButtons"></div>');if(c){if(c["confirm"]||c["input"]){$(".aButtons").append('<button value="ok">'+ c["textOk"]+"</button>");$(".aButtons").append('<button value="cancel">'+ c["textCancel"]+"</button>")}else if(c["verify"]){$(".aButtons").append('<button value="ok">'+ c["textYes"]+"</button>");$(".aButtons").append('<button value="cancel">'+ c["textNo"]+"</button>")}else{$("div.iposbottom").hide()}}else{$(".aButtons").append('<button value="ok">Ok</button>')}
$(document).keydown(function(a){if($(".appriseOverlay").is(":visible")){if(a.keyCode==13){$('.aButtons > button[value="ok"]').click()}
if(a.keyCode==27){$('.aButtons > button[value="cancel"]').click()}}});var j=$(".aTextbox").val();if(!j){j=false}
$(".aTextbox").keyup(function(){j=$(this).val()});$(".appriseOverlay").click(function(){$(".appriseOverlay").remove();$(".appriseOuter").remove();if(d){var a=$(this).attr("value");if(a=="ok"){if(c){if(c["input"]){d(j)}else{d(true)}}else{d(true)}}else if(a=="cancel"){d(false)}}})
$(".aButtons > button,a.close").click(function(){$(".appriseOverlay").remove();$(".appriseOuter").remove();if(d){var a=$(this).attr("value");if(a=="ok"){if(c){if(c["input"]){d(j)}else{d(true)}}else{d(true)}}else if(a=="cancel"){d(false)}}})
$(document).keydown(function(e){if(e.keyCode==27){$(".appriseOverlay").click();}});}
function EnterKey(a){13==(window.event?window.event.keyCode:a.which)&&do_search()}
function do_search(a){if(searchid=$(".tgt-autocomplete-activeItem a").attr("href"))return window.location.href=searchid,!1;1==a&&(query=$("input[name='query']").val(),window.location.href="./tim-kiem/"+ query+".html");return!1}
function setupplayer(a){var href=$('a#ep_'+ a).attr("href");var _title=$('a#ep_'+ a).data("title").replace('tập','Tập');$('h1.main-title a').html(_title);window.history.pushState(null,null,href);jQuery('title').text(_title+' | '+ jQuery('a#ep_'+ a).parent().find('.svname').text().replace(':','')+' | AnimeTVN');$("a.playing").removeClass("playing");$("#ep_"+ a).addClass("playing");$('html,body').animate({scrollTop:$("#main").offset().top},'slow');$("[name='_epid']").val(a);$("#taiphim").html("");}
function load_player_to(id){$.post(ajaxurl,{ipos_get_player_gkphp:1,epid:id},function(a){$(".loadplayer").html(a);});}
function load_player_js_to(id){$.post(ajaxurl,{ipos_get_player_js:1,epid:id},function(a){player.dispose();$(".load_player_js").html(a);player=videojs('#video-js',{plugins:{resolutionSelector:{}}},function(){});player.play()});}
$(function(){$("button[name='next']").on("click",function(e){e.preventDefault();var arr=$("#_listep .svep a");$.each(arr,function(key,value){if($(this).hasClass("playing")&&key<(arr.length- 1)){var n=(key+ 1),url=arr[n].toString(),url=url.substring(url.lastIndexOf('/f')+ 2),id=url.match(/^(\d+)-/)[1];$("name=['limitnum']").val(id);if($('.tab_act_jw').hasClass('active')){$(".load_player_js").removeClass('playing');load_player_to(id);}else if($('.tab_act_js').hasClass('active')){load_player_js_to(id);}
setupplayer(id);return false;}});});$("button[name='back']").on("click",function(e){e.preventDefault();var arr=$("#_listep .svep a");$.each(arr,function(key,value){if($(this).hasClass("playing")&&key>=1){var n=(key- 1),url=arr[n].toString(),url=url.substring(url.lastIndexOf('/f')+ 2),id=url.match(/^(\d+)-/)[1];$("name=['limitnum']").val(id);if($('.tab_act_jw').hasClass('active')){$(".load_player_js").removeClass('playing');load_player_to(id);}else if($('.tab_act_js').hasClass('active')){load_player_js_to(id);}
setupplayer(id);return false;}});});});function _light(){$('html,body').animate({scrollTop:$("#main").offset().top},'slow');if(!cookie_light){$("div.light_on").fadeIn();$("a._light").html("Bật đèn");cookie_light=true}else{$("div.light_on").fadeOut();$("a._light").html("Tắt đèn");cookie_light=false}
return false}
$(document).ready(function(){$("div.light_on").click(function(){$('div.light_on').fadeOut();$("a._light").html("Tắt đèn");cookie_light=false});});function _autonext(){if(!pautonext){$("a._autonext span").html("Bật");$.cookie("autonext","1");pautonext=true}else{$("a._autonext span").html("Tắt");$.cookie("autonext","0");pautonext=false}
return false}
function _droplist(a){if(droplist){$("div.drop_list").hide();droplist=false}else{$("div.drop_list").hide();$(a).show();droplist=true}
return false}
function _lTxt(a,b){$("#_txt_l"+ b+" span#_load").html($(a).attr("rel"));$("#drop_list_"+ b+" a.activer").removeClass("activer");$(a).addClass("activer");$("div.drop_list").hide();droplist=false;return false}
function _showfilm(a){if(a==0){$("#_txt_l1 span#_load").html($("#drop_list_1 a.activer").attr("rel"));$("#_txt_l2 span#_load").html($("#drop_list_2 a.activer").attr("rel"));$("#_txt_l3 span#_load").html($("#drop_list_3 a.activer").attr("rel"))}else{var b="";var c="";var d=$("#drop_list_1 a.activer").attr("did");var e=$("#drop_list_2 a.activer").attr("did");var f=$("#drop_list_3 a.activer").attr("did");explode=a.split("?");if(explode[1]){_ex="&";explodez=explode[1].split("order=");if(explodez[1]){_ex="?"+ explodez[0];a=explode[0]}}else _ex="?";if(d)var b="&categoryid="+ d;if(f)var c="&countryid="+ f;window.location.href=a+ _ex+"order="+ e+ b+ c}
return false}
function loginsubmit(){var a=$("input[name='username']").val();var b=$("input[name='password']").val();var c=$("input[name='remember']").val();var d={ipos_login:1,username:a,password:b,remember:c};$.post(ajaxurl,d,function(a){if(a==1){location.reload()}else{jAlert(a,"Thông báo")}});return false}
function commentsubmit(){var a=new Validator("commentz");a.addValidation("comment","req","Vui lòng nhập nội dung");a.addValidation("comment","minlen=30","Nội dung chứa từ 30 đên 900 ký tự");a.addValidation("comment","maxlen=900","Nội dung chứa từ 30 đên 900 ký tự");forCheck=a.formobj.onsubmit();if(forCheck){var a=$("textarea[name='comment']").val();var b=$("input[name='phimid']").val();var c={ipos_camnhan:1,camnhantxt:a,phimid:b};jAlert("Gửi thành công, cảm ơn bạn đã báo lỗi!","Thông báo")
$.post(ajaxurl,c,function(a){if(a==2){_Login()}
if(a==3){jAlert('Tốc độ quá nhanh, xin chờ trong ít phút',"Thông báo")}else{commentlist(a,1)}});}
return false}
function commentlist(phimid,page){var a={ipos_commentlist:1,phimid:phimid,page:page};$.post(ajaxurl,a,function(a){document.getElementById("comment-list").innerHTML=a;});return false}
function _Login(){var a='<form id="_frmLogin" onsubmit="return loginsubmit();"><div id="loginInput">'+'<p class="items-form"><label>Tên tài khoản</label><input name="username" type="text"></p>'+'<p class="items-form"><label>Mật khẩu</label><input name="password" type="password"></p>'+'<input checked name="remember" type="checkbox" value="1" /> Ghi nhớ đăng nhập</p>'+'<p class="items-form" style="float: left;"><input style="display: block; float: left;" class="button-input-box" type="submit" value="Đăng nhập"><a style="display: block; float: left;" href="'+ login_fb_url+'"><img width="38" src="http://animetvn.com/template/img/fb.png" alt="" /></a></p>'+'<div style="clear: both"></div>'+'<p class="items-form txtcenter"><a href="javascript:_Register();">Đăng ký thành viên</a><a class="line" href="javascript:_ForGot();">Quên mật khẩu</a></p>'+"</div></form>";apprise("Đăng nhập",a,{animate:true})}
function forgotsubmit(){var a=new Validator("forgotz");a.addValidation("email","req","Vui lòng nhập địa chỉ Email");a.addValidation("email","email");a.addValidation("user","req","Vui lòng nhập tên đăng nhập");a.addValidation("passnew","req","Vui lòng nhập mật khẩu mới");a.addValidation("captcha","req","Vui lòng nhập mã xác nhận");forCheck=a.formobj.onsubmit();if(forCheck){var a=$("input[name='email']").val();var b=$("input[name='captcha']").val();var c=$("input[name='user']").val();var d=$("input[name='passnew']").val();var e={ipos_forgot:1,email:a,captcha:b,user:c,passnew:d};$.post(ajaxurl,e,function(a){if(a==1){refreshCaptcha();jAlert("Mật khẩu của bạn đã dược đổi lại, bạn có thể dùng mật khẩu này để đăng nhập","Thông báo")}else{jAlert(a,"Thông báo")}});}
return false}
function _ForGot(){var a='<form name="forgotz" id="_frmLogin" onsubmit="return false;"><div id="loginInput">'+'<p class="items-form"><label>Email của bạn</label><input name="email" type="text"></p>'+'<p class="items-form"><label>Tên đăng nhập</label><input name="user" type="text"></p>'+'<p class="items-form"><label>Mật khẩu mới</label><input name="passnew" type="password"></p>'+'<p class="items-form captcha"><label>Mã xác nhận (<a href="javascript: refreshCaptcha();">Đổi mã khác</a>)</label>'+'<input name="captcha" type="text">'+'<img id="captchaimg" src="'+ IPOS_DOMAIN+"/captcha.php?rand="+ Math.random()+'"></p>'+'<p class="items-form"><input class="button-input" type="submit" onclick="return forgotsubmit();" value="Xác nhận"></p>'+"</div></form>";apprise("Bạn quên mật khẩu?",a,{animate:true})}
function dangKy(){var a=new Validator("register");a.addValidation("username","req","Vui lòng nhập tên tài khoản");a.addValidation("username","minlen=6","Tên tài khoản chứa từ 6 đên 12 ký tự");a.addValidation("username","maxlen=12","Tên tài khoản chứa từ 6 đên 12 ký tự");a.addValidation("password","req","Vui lòng nhập mật khẩu");a.addValidation("repassword","req","Vui lòng nhập lại mật khẩu");a.addValidation("email","req","Vui lòng nhập địa chỉ Email");a.addValidation("email","email");a.addValidation("fullname","req","Vui lòng nhập họ tên của bạn");a.addValidation("year","req","Vui lòng nhập năm sinh của bạn");a.addValidation("year","numeric","Dữ liệu phải là số");a.addValidation("fullname","req","Vui lòng nhập họ tên của bạn");a.addValidation("sex","req","Vui lòng chọn giới tính của bạn");a.addValidation("captcha","req","Vui lòng nhập mã xác nhận");regCheck=a.formobj.onsubmit();if(regCheck){var b=$("input[name='username']").val();var c=$("input[name='password']").val();var d=$("input[name='repassword']").val();var e=$("input[name='email']").val();var f=$("input[name='fullname']").val();var g=$("select[name='day']").val();var h=$("select[name='month']").val();var i=$("input[name='year']").val();var j=$("input[name='sex']").val();var k=$("input[name='captcha']").val();var l=g+"-"+ h+"-"+ i;if(c!=d)jAlert("Mật khẩu và mật khẩu xác nhận không giống nhau!","Thông báo");else{var m={ipos_reg:1,username:b,password:c,repassword:d,email:e,fullname:f,birthday:l,sex:j,captcha:k};$.post(ajaxurl,m,function(a){if(a==1){jAlert("Chúc mừng bạn bạn đã đăng ký thành công!","Thông báo")}else{jAlert(a,"Thông báo");refreshCaptcha()}})}
return false}}
function _Register(){var a='<div id="register"><form name="register" method="post">'+'<div class="registerLeft">'+'<p class="items-form"><label>Tên tài khoản</label><input name="username" type="text"></p>'+'<p class="items-form"><label>Mật khẩu</label><input name="password"  type="password"></p>'+'<p class="items-form"><label>Xác nhận mật khẩu</label><input name="repassword"  type="password"></p>'+'<p class="items-form"><label>Email</label><input name="email" type="text" value="'+ fb_email+'"></p>'+'<p class="items-form txtfaq"><input checked name="faq" type="checkbox" value="1" /> Tôi đồng ý với Quy định của AnimeTVN.</p>'+"</div>"+'<div class="registerRight">'+'<p class="items-form"><label>Họ tên</label><input name="fullname" type="text" value="'+ fb_name+'"></p>'+'<p class="items-form birthday"><label>Ngày sinh (Ngày/Tháng/Năm)</label>'+'<select name="day"><option value="01">01</option><option value="02">02</option><option value="03">03</option><option value="04">04</option><option value="05">05</option><option value="06">06</option><option value="07">07</option><option value="08">08</option><option value="09">09</option><option value="10">10</option><option value="11">11</option><option value="12">12</option><option value="13">13</option><option value="14">14</option><option value="15">15</option><option value="16">16</option><option value="17">17</option><option value="18">18</option><option value="19">19</option><option value="20">20</option><option value="21">21</option><option value="22">22</option><option value="23">23</option><option value="24">24</option><option value="25">25</option><option value="26">26</option><option value="27">27</option><option value="28">28</option><option value="29">29</option><option value="30">30</option><option value="31">31</option></select>'+'<select name="month"><option value="01">01</option><option value="02">02</option><option value="03">03</option><option value="04">04</option><option value="05">05</option><option value="06">06</option><option value="07">07</option><option value="08">08</option><option value="09">09</option><option value="10">10</option><option value="11">11</option><option value="12">12</option></select>'+'<input type="text" name="year">'+'<p class="items-form"><label>Giới tính</label>'+'<select name="sex"><option value="">Chọn giới tính</option><option value="0">Nam</option><option value="1">Nữ</option></select>'+"</p>"+'<p class="items-form captcha"><label>Nhập mã xác nhận (<a href="javascript: refreshCaptcha();">Đổi mã khác</a>)</label><input name="captcha" type="text">'+'<img id="captchaimg" src="'+ IPOS_DOMAIN+"/captcha.php?rand="+ Math.random()+'"></p>'+'<p class="items-form"><input class="button-input" type="submit" onclick="return dangKy();" value="Xác nhận"></p>'+"</div>"+'<div class="clr"></div></form</div>';apprise("Đăng ký thành viên",a,{animate:true})}
function _request(){var a='<form name="requestz" id="_frmLogin" onsubmit="return false;"><div id="loginInput">'+'<p class="items-form"><label>Email của bạn</label><input name="email" type="text"></p>'+'<p class="items-form"><label>Nội dung:</label></p><textarea name="info" rows="7" tabindex="4"></textarea>'+'<p class="items-form captcha"><label>Mã xác nhận (<a href="javascript: refreshCaptcha();">Đổi mã khác</a>)</label>'+'<input name="captcha" type="text">'+'<img id="captchaimg" src="'+ IPOS_DOMAIN+"/captcha.php?rand="+ Math.random()+'"></p>'+'<p class="items-form"><input class="button-input" type="submit" onclick="return requestsubmit();" value="Xác nhận"></p>'+"</div></form>";apprise("Bạn muốn yêu cầu gì?",a,{animate:true})}
function g_searchUser(){var key=$("#gq").val();if(key!='Tìm kiếm thành viên...'&&key!=''){key=key.replace(/\s+/g,'-');window.location.href=IPOS_DOMAIN+'/tim-kiem-thanh-vien/'+ key+'.html';}
return false;}
function requestsubmit(){var a=new Validator("requestz");a.addValidation("email","req","Vui lòng nhập địa chỉ Email");a.addValidation("email","email");a.addValidation("info","req","Nhập nội dung cần yêu cầu");a.addValidation("captcha","req","Vui lòng nhập mã xác nhận");forCheck=a.formobj.onsubmit();if(forCheck){var a=$("input[name='email']").val();var b=$("textarea[name='info']").val();var c=$("input[name='captcha']").val();var d={ipos_r:1,email:a,info:b,captcha:c};$.post(ajaxurl,d,function(a){if(a==1){refreshCaptcha();jAlert("Gửi thành công, chúng tôi sẽ kiểm tra và phản hồi cho bạn trong vòng 24 giờ","Thông báo")}else{jAlert(a,"Thông báo")}});}
return false}
function _loiphim(){var a='<form name="requestz" id="_frmLogin" onsubmit="return false;"><div id="loginInput">'+'<p class="items-form"><label>Mời bạn báo chi tiết lỗi theo mẫu:<br />Tên phim:<br />Server lỗi:<br />Tên tập lỗi:<br />Loại lỗi: (Không xem được, sai tập, sai/lỗi sub,...)</label></p><textarea style="width: 260px;" name="info1" rows="7" tabindex="4"></textarea>'+'<p class="items-form captcha"><label>Mã xác nhận (<a href="javascript: refreshCaptcha();">Đổi mã khác</a>)</label>'+'<input name="captcha" type="text">'+'<img id="captchaimg" src="'+ IPOS_DOMAIN+"/captcha.php?rand="+ Math.random()+'"></p>'+'<p class="items-form"><input class="button-input" type="submit" onclick="return requestsubmit1();" value="Báo lỗi"></p>'+"</div></form>";apprise("Box báo lỗi",a,{animate:true})}
function requestsubmit1(){var a=new Validator("requestz");a.addValidation("info1","req","Nhập nội dung cần yêu cầu");a.addValidation("captcha","req","Vui lòng nhập mã xác nhận");forCheck=a.formobj.onsubmit();if(forCheck){var a=$("input[name='email1']").val();var b=$("textarea[name='info1']").val();var c=$("input[name='captcha']").val();var d={ipos_r1:1,email1:a,info1:b,captcha:c};$.post(ajaxurl,d,function(a){if(a==1){refreshCaptcha();jAlert("Cảm ơn bạn đã thông báo lỗi, chúng tôi sẽ sửa trong thời gian sớm nhất.","Thông báo")}else{jAlert(a,"Thông báo")}});}
return false}
function refreshCaptcha(){var a=document.images["captchaimg"];a.src=a.src.substring(0,a.src.lastIndexOf("?"))+"?rand="+ Math.random()*1e3}
function _FollowLoad(a,b){var c={ipos_follow:1,add_id:a,remove_id:b};$.post(ajaxurl,c)}
function _ViewedLoad(a,b){var c={ipos_viewed:1,add_id:a,remove_id:b};$.post(ajaxurl,c)}
function _watchingFilmLoad(a,b)
{var c={ipos_watching_film:1,add_id:a,remove_id:b};$.post(ajaxurl,c)}
function _LikeLoad(a,b){var c={ipos_like:1,add_id:a,remove_id:b};$.post(ajaxurl,c)}
function _AddLike(a){if(a==0){_Login()}else{if($("a[data-fwba='"+a+"']").hasClass('gnarty_film_already')){jAlert("Phim này đã có trong danh sách của bạn rồi!","Thông báo");}else{_LikeLoad(a,0);jAlert("Đã thêm phim vào danh sách yêu thích!","Thông báo");}}}
function _RemoveLike(a){_LikeLoad(0,a);$("#pl_"+ a).remove()}
function submit_gold(){var a=$("select[name='action']").val();var b=$("input[name='captcha']").val();if(!a)jAlert("Bạn chưa chọn mệnh giá đổi!");else if(!b)jAlert("Bạn chưa nhập mã an toàn!");else{var c={ipos_submit_gold:1,action:a,captcha:b};$.post(ajaxurl,c,function(a){if(a==1){jAlert("Đã kích hoạt xong, hệ thống sẽ tự động chuyển về trang chủ!");setTimeout("window.location = '/';",2e3)}else{refreshCaptcha();jAlert(a)}})}
return false}
function _playMovie(a){var b={ipos_playMovie:1,phimid:a};$.post(ajaxurl,b,function(a){if(a==1){location.reload()}else if(a==2){_Login()}else{jAlert(a)}});return false}
function _PlayMovieZ(a){$.post(ajaxurl,{ipos_playMovieZ:1,phimid:a},function(a){var b='<iframe scrolling="no" src="'+ a+'" frameborder="0" allowtransparency="true" style="overflow:hidden;border:0;margin:0;width:600px; height:382px; background:#fff;">';apprise("Xem nhanh",b,{animate:true})})}
function update_error(a){if(a==0)_Login();else{var b=parseInt($(".playing").attr("rel"));var c=parseInt($("input[name='phimid']").val());$.post(ajaxurl,{ipos_error:1,epid:b,phimid:c},function(){jAlert("Cảm ơn bạn đã báo phim lỗi, chúng tôi sẽ kiểm tra và khắc phục trong thời gian sớm nhất.")})}}
function like_phim(a,b){$.post(ajaxurl,{ipos_likephim:1,phimid:a},function(a){document.getElementById("likefilm").innerHTML='<a id="vtips" class="menu_xemphim">'+ a+' lượt thích.</a>';})}
var playerw="100%";var playerh="100%";var servertop=0;var cookie_light=false;var pautonext=$.inArray($.cookie("autonext"),new Array(null,"1"))!=-1;var droplist=false;var cookie_like=false;var cookie_send=false;var cookie_notice=false;$(document).ready(function(){$("#gallery a").lightBox({fixedNavigation:true});$("#_txt_l1,#_txt_l2,#_txt_l3,#_go_,#vtips").tipsy({gravity:"s"});$("#vtip a").tipsy({title:function(){return document.getElementById(this.getAttribute("iposmovie-id")).innerHTML},gravity:"e",html:true,opacity:1});$("#logz").hover(function(){$("#logz a.registerb").addClass("showUser");$("ul#blogz").css({visibility:"visible",display:"none"}).show()},function(){$("#logz a.registerb").removeClass("showUser");$("ul#blogz").css({visibility:"hidden"})});$("#logh").hover(function(){if(!cookie_send){var b={ipos_likebox:1};$.post(ajaxurl,b,function(a){if(a==1){jAlert("Hộp phim của bạn hiện không có phim nào!","Thông báo")}else{$("#like_list").html(a);cookie_send=true}})}
if(!cookie_like){$("#top_menu a.like").addClass("act");$("#like_list").show();cookie_like=true}else{$("#top_menu a.like").removeClass("act");$("#like_list").hide();cookie_like=false}
$("#logh a.loginb").addClass("showUser");$("ul#like_list").css({visibility:"visible",display:"none"}).show()},function(){$("#logh a.loginb").removeClass("showUser");$("ul#like_list").css({visibility:"hidden"})});$("#searchInput").autocomplete(ajaxurl+"?post=search",{width:395,max:20,highlight:!1,scroll:!1});$("#close-scroll-notice").click(function(){$('#notice-show').remove();var b={ipos_notice:1};$.post(ajaxurl,b,function(a){return false})});$(window).scroll(function(){if($(this).scrollTop()>0){$('#notice-show').fadeIn();}});$(function(){$('#totop').click(function(){$('body,html').animate({scrollTop:0});});});$(document).ready(function(){$('#tobottom').click(function(){$('html, body').animate({scrollTop:$(document).height()},'slow');return false;});$('#downloadfilm').click(function(){var epid=$(this).attr('data-id');$.post(ajaxurl,{ipos_downphim:1,epid:epid},function(a){apprise("Tải tập Anime này",a,{animate:true})});return false;});});$("#_playtrailer").click(function(){var a=$(this).attr("rel");player="Chưa có trailer cho bộ phim này!";if(a){a=a.replace(/watch\?v=/g,"embed/");a=a+"?showinfo=0&autoplay=1";player='<iframe width="640" height="395" src="'+ a+'" frameborder="0" allowfullscreen></iframe>'}
apprise("Xem trailer",player,{animate:true});return false});});function TaiAnime(){var epid=$("[name='_epid']").val();$("#taiphim").html("");var xmlhttp;if(window.XMLHttpRequest){xmlhttp=new XMLHttpRequest();}else{xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");}
xmlhttp.onreadystatechange=function(){if(xmlhttp.readyState==4&&xmlhttp.status==200){document.getElementById("taiphim").innerHTML=xmlhttp.responseText;}}
xmlhttp.open("POST","include/downanime.php",true);xmlhttp.setRequestHeader("Content-type","application/x-www-form-urlencoded");xmlhttp.send("epid="+ epid);};function dhLoadMoreUrl($epid,$next)
{$.ajax({url:ajaxurl,type:'POST',data:{ipos_get_player_gkphp:true,epid:$epid,next:parseInt($next)},}).done(function(a){$(".loadplayer").html(a);}).fail(function(){console.log("error");});}
function dh_request_film_tab($type,$page,$target)
{$.ajax({url:ajaxurl,type:'POST',data:{'home-film-tab':true,'film':$type,'page':$page},}).done(function(json){json=jQuery.parseJSON(json);if(json.success){$target.find('ul').html(json.html);$target.find('.home-pagination').html(json.pagination);$("img.lazyload").unveil();dh_load_tip();}}).fail(function(){alert('Đã xảy ra lỗi khi tải phim, vui lòng refresh và thử lại.');});}
function dh_load_tip()
{$('.items').each(function(){var xOffset=-10;var yOffset=10;$(this).unbind().hover(function(e){this.content=$(this).parent().find('.f-description').html();this.top=(e.pageY+ yOffset);this.left=(e.pageX+ xOffset);if(this.content!=null){$('body').append('<div id="vtip" class="f-description">'+ this.content+'</div>');$('div#vtip').css("top",this.top+"px").css("left",this.left+"px").fadeIn("slow");}},function(){$("div#vtip").fadeOut("slow").remove();}).mousemove(function(e){this.top=(e.pageY+ yOffset);this.left=(e.pageX+ xOffset);$("div#vtip").css("top",this.top+"px").css("left",this.left+"px");});});}
(function(){var im2=new Image();jQuery(function($){var w=$(window),dimmer=$('<div style="position:fixed;z-index:-1;top:0;left:0;display:none;background-color:#000;"><\/div'),im1=$('#onoff').toggle(lightsOut,lightsOn).css({zIndex:7,position:'relative',cursor:'pointer'}).attr('src');function dresize(){dimmer.css({height:w.height(),width:w.width()});}
function lightsOut(){this.title=this.html='Bật đèn';this.src=im2.src;dimmer.stop().css({zIndex:5}).animate({opacity:0.9,duration:'slow'});}
function lightsOn(){this.title=this.html='Tắt đèn';this.src=im1;dimmer.stop().css({zIndex:-1}).animate({opacity:0,duration:'slow'});}
dresize();$('body').append(dimmer.css({opacity:0,display:'block'}));w.resize(dresize);});})();